window.NODE_TYPES = window.NODE_TYPES || {};
Object.assign(window.NODE_TYPES, {
  // [TASK] - Orange Theme
  // [TASK] - Orange Theme
  SegmentationTask: {
    title: "Segmentation Task",
    color: "#f97316", // Orange 500
    inputs: ["model_args", "optim_args", "scheduler_args", "tiled_inference"],
    outputs: ["task"],
    params: [
      {
        key: "loss",
        label: "LOSS FUNCTION",
        type: "select",
        options: ["ce", "dice", "focal"],
        default: "ce",
      },
      { key: "num_classes", label: "NUM CLASSES", type: "number", default: 2 },
      {
        key: "ignore_index",
        label: "IGNORE INDEX",
        type: "number",
        default: -1,
      },
      {
        key: "model_factory",
        label: "FACTORY",
        type: "select",
        options: ["EncoderDecoderFactory", "PrithviModelFactory"],
        default: "EncoderDecoderFactory",
      },
      {
        key: "freeze_backbone",
        label: "FREEZE BACKBONE",
        type: "select",
        options: ["True", "False"],
        default: "False",
      },
      {
        key: "freeze_decoder",
        label: "FREEZE DECODER",
        type: "select",
        options: ["True", "False"],
        default: "False",
      },
      {
        key: "freeze_head",
        label: "FREEZE HEAD",
        type: "select",
        options: ["True", "False"],
        default: "False",
      },
      { key: "plot_on_val", label: "PLOT ON VAL", type: "text", default: "10" },
      { key: "class_names", label: "CLASS NAMES", type: "text", default: "" },
      {
        key: "test_dataloaders_names",
        label: "TEST DLS NAMES",
        type: "text",
        default: "",
      },
      {
        key: "output_on_inference",
        label: "OUT ON INFERENCE",
        type: "text",
        default: "prediction",
      },
      {
        key: "output_most_probable",
        label: "OUT MOST PROB",
        type: "select",
        options: ["True", "False"],
        default: "True",
      },
      {
        key: "path_to_record_metrics",
        label: "METRICS PATH",
        type: "text",
        default: "",
      },
      {
        key: "tiled_inference_on_testing",
        label: "TILED TESTING",
        type: "select",
        options: ["True", "False"],
        default: "False",
      },
      {
        key: "tiled_inference_on_validation",
        label: "TILED VAL",
        type: "select",
        options: ["True", "False"],
        default: "False",
      },
    ],
  },
  PixelwiseRegressionTask: {
    title: "Regression Task",
    color: "#f97316", // Orange 500
    inputs: ["model_args", "optim_args", "scheduler_args", "tiled_inference"],
    outputs: ["task"],
    params: [
      {
        key: "loss",
        label: "LOSS FUNCTION",
        type: "select",
        options: ["rmse", "mae", "huber"],
        default: "rmse",
      },
      {
        key: "ignore_index",
        label: "IGNORE INDEX",
        type: "number",
        default: -1,
      },
      {
        key: "model_factory",
        label: "FACTORY",
        type: "select",
        options: ["PrithviModelFactory", "EncoderDecoderFactory"],
        default: "PrithviModelFactory",
      },
      {
        key: "freeze_backbone",
        label: "FREEZE BACKBONE",
        type: "select",
        options: ["True", "False"],
        default: "False",
      },
      {
        key: "freeze_decoder",
        label: "FREEZE DECODER",
        type: "select",
        options: ["True", "False"],
        default: "False",
      },
      {
        key: "freeze_head",
        label: "FREEZE HEAD",
        type: "select",
        options: ["True", "False"],
        default: "False",
      },
      { key: "plot_on_val", label: "PLOT ON VAL", type: "text", default: "10" },
      { key: "class_names", label: "CLASS NAMES", type: "text", default: "" },
      {
        key: "test_dataloaders_names",
        label: "TEST DLS NAMES",
        type: "text",
        default: "",
      },
      {
        key: "output_on_inference",
        label: "OUT ON INFERENCE",
        type: "text",
        default: "prediction",
      },
      {
        key: "output_most_probable",
        label: "OUT MOST PROB",
        type: "select",
        options: ["True", "False"],
        default: "True",
      },
      {
        key: "path_to_record_metrics",
        label: "METRICS PATH",
        type: "text",
        default: "",
      },
      {
        key: "tiled_inference_on_testing",
        label: "TILED TESTING",
        type: "select",
        options: ["True", "False"],
        default: "False",
      },
      {
        key: "tiled_inference_on_validation",
        label: "TILED VAL",
        type: "select",
        options: ["True", "False"],
        default: "False",
      },
    ],
  },
  CustomTask: {
    title: "Custom Task",
    color: "#f97316",
    inputs: ["model_args", "optim_args", "scheduler_args", "tiled_inference"],
    outputs: ["task"],
    params: [
      {
        key: "class_path",
        label: "CLASS PATH",
        type: "text",
        default: "terratorch.tasks.MyTask",
      },
      {
        key: "model_factory",
        label: "FACTORY",
        type: "select",
        options: ["EncoderDecoderFactory", "PrithviModelFactory"],
        default: "EncoderDecoderFactory",
      },
    ],
    allowCustomParams: true,
  },
});
